apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: kirand18/project-repository
        ports:
        - containerPort: 3005
        env:
        - name: MONGO_URI
          value: "mongodb+srv://kirand1895_db_user:kiran1234@cluster-mongo.fqlnbfx.mongodb.net/?appName=Cluster-mongo/mongodb"
